# Synthetic VecAdd: exercises buffer init supplied as an existing .bin file.
#
# bmm/ covers `bytes` init (data generated in launch.py, written to buf_init/
# on save). This example covers the other init source -- a `.bin` file that
# already exists on the host -- and puts all three encodings in one descriptor
# so the generated launches.json shows them side by side:
#
#   a: init=Path       -> JSON holds vec_a.bin's own path; file is NOT copied
#                         into buf_init/, and save_launches() never prunes it
#   b: init=bytes      -> written to buf_init/k0_a1.bin; JSON holds that path
#   c: no init         -> "init": null
#
# Path init is validated at descriptor-import time (kernel_launch's
# _validate_buffer): the file must exist and its size must equal the buffer
# size EXACTLY -- unlike bytes init, which may be shorter than the buffer.
#
# The path is resolved absolute here because the JSON stores it verbatim: the
# host driver that later loads launches.json runs from an unrelated cwd, so a
# relative path would resolve against the wrong directory.
#
# Purely illustrative, like pipeline/ -- this ELF path doesn't point at a real
# kernel. gen_launches_json.py / parse_launches / check_launch only need the
# path string.
#
# vec_a.bin is checked in: 16 little-endian int32 values, 1..16. Regenerate with
#   python3 -c "import struct,pathlib; pathlib.Path('vec_a.bin').write_bytes(struct.pack('<16i',*range(1,17)))"
import struct
from pathlib import Path
from kernel_launch import IN, KernelLaunch, buffer, scalar, OUT

STAGE_DIR = Path(__file__).resolve().parent

N = 16
VEC_BYTES = N * 4  # int32 elements

LAUNCHES = [
    KernelLaunch(
        elf=str(STAGE_DIR / "VecAdd.elf"),
        entry="vecAddStart",
        grid=(1, 1, 4),  # 1x1 CR grid, 4 CEs
        args=[  # order must match argument order in kernel entry function
            # a: input from a pre-existing .bin file (size must match exactly)
            buffer(VEC_BYTES, IN, init=STAGE_DIR / "vec_a.bin", name="a"),
            # b: input from host-generated bytes, for contrast
            buffer(VEC_BYTES, IN, init=struct.pack(f"<{N}i", *range(100, 100 + N)), name="b"),
            buffer(VEC_BYTES, OUT, name="c"),  # c: output vector
            scalar("i32", N, name="n"),        # n: element count
        ],
    )
]
